blank_issues_enabled: false
contact_links:
  - name: Security Vulnerability
    url: https://github.com/the-nash-group/.github/security/policy
    about: Please report security vulnerabilities through our responsible disclosure process
  - name: The Chronicles (Documentation)
    url: https://github.com/the-nash-group/docs-chronicles
    about: Consult The Chronicles for answers to common questions
  - name: Community Discussions
    url: https://github.com/orgs/the-nash-group/discussions
    about: Join the immortals in discussing architecture and philosophy